# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push PHP8 20.04
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ghcr.io/flhuber/lamp:latest,ghcr.io/flhuber/lamp:latest-2004-php8
          push: true
          build-args: PHP_VERSION=8.0
          file: ./2004/Dockerfile
      -
        name: Build and push PHP7 20.04
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ghcr.io/flhuber/lamp:latest-2004-php7
          push: true
          build-args: PHP_VERSION=7.0
          file: ./2004/Dockerfile
      -
        name: Build and push PHP8 18.04
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ghcr.io/flhuber/lamp:latest-1804-php8
          push: true
          build-args: PHP_VERSION=8.0
          file: ./1804/dockerfile
      -
        name: Build and push PHP7 18.04
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ghcr.io/flhuber/lamp:latest-1804-php7
          push: true
          build-args: PHP_VERSION=7.0
          file: ./1804/Dockerfile
