# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build Main
        run: docker build --build-arg PHP_VERSION=8.0 -t=ghcr.io/flhuber/lamp:latest --push -f ./2004/Dockerfile .
      -
        name: Build 20.04 PHP8
        run: docker build --build-arg PHP_VERSION=8.0 -t=ghcr.io/flhuber/lamp:latest-2004-php8 -f ./2004/Dockerfile .     
      -
        name: Build 20.04 PHP7
        run: docker build --build-arg PHP_VERSION=7.4 -t=ghcr.io/flhuber/lamp:latest-2004-php7 -f ./2004/Dockerfile .  
      -
        name: Build 18.04 PHP8
        run: docker build --build-arg PHP_VERSION=8.0 -t=ghcr.io/flhuber/lamp:latest-1804-php8 -f ./1804/Dockerfile .     
      -
        name: Build 18.04 PHP7
        run: docker build --build-arg PHP_VERSION=7.4 -t=ghcr.io/flhuber/lamp:latest-1804-php7 -f ./1804/Dockerfile .    
